  GNU nano 4.8                                                                                           Modified  
name: Node.js CI
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: build Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with:
                node-version: [12.x, 14.x, 16.x]
            - name: Install Packages and Build Application
              run: |
                npm install -g @vue/cli yarn
                npm run build

            - name: Deploy
              uses: s0/git-publish-subdir-action@master
              env:
                REPO: self
                BRANCH: main
                FOLDER: dist
        GITHUB_TOKEN: ${{ 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 }}
